name: Build
on:
  push:
    branches: [ "main" ]
  schedule:
      - cron: "0 0 * * 0"
  workflow_dispatch:
      inputs:
        docker_tag:
          description: 'Docker tag'
          required: true
          default: 'latest' 
          type: string
env:
  BUILDKIT_IMAGE: jkaninda/toolkit
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
           "${{env.BUILDKIT_IMAGE}}:0.1"
           "${{env.BUILDKIT_IMAGE}}:latest"
